start:
  from:
    x: -469.7
    y: 4
    z: -769
    world: world
  to:
    x: -469.7
    y: 4
    z: -774
    world: world
end:
  from:
    x: -503.7
    y: 9
    z: -773.7
    world: world
  to:
    x: -503.7
    y: 9
    z: -768.7
    world: world
spawn:
  x: -461.20962247618723
  y: 4.0
  z: -770.8694042772668
  yaw: 91.34296
  pitch: 25.199991
  world: world
