start:
  from:
    x: -469.7
    y: 4
    z: -769
    world: world
  to:
    x: -469.7
    y: 4
    z: -774
    world: world
end:
  from:
    x: -503.7
    y: 4
    z: -773
    world: world
  to:
    x: -503.7
    y: 4
    z: -768
    world: world